### PR TITLE
Fix non-standard homepage location

### PR DESCRIPTION
**Pull request by ewellinger**
Adds the option to specify the homepage uri in your configuration.  Tested on my own installation and this appears to be fixing the issue when you have a non-standard homepage location.

Fixes issue #14

### CODE REVIEW

**Comment by timvink** [comment]
Thanks!

This more of a workaround rather than solving the core issue: dynamically from every page figure out the path to the javascript assets.

Going to experiment a bit and see if I find a better alternative.

**Comment by ewellinger** [comment]
I actually might have an idea how this could happen in a more holistic way. I'll try it out and see if I can get something working.
Right now, I had to tweak the overall structure of our documentation to leverage the `mkdocs-charts-plugin`, which I'm hoping to revert once this issue is solved. Even if it's not the cleanest, getting a workaround might be better than nothing.

**Comment by ewellinger** [comment]
Alright, I just pushed an update. Let me know what you think.

Sorry for the other changes, those happened automatically with Black enabled in my IDE.

**Comment by timvink** [comment]
Yes, that will work. 

I vaguely remember not using the `docs_dir` initially, because it will break compatibility with plugins like https://github.com/oprypin/mkdocs-gen-files  and https://github.com/backstage/mkdocs-monorepo-plugin .

But I think non-standard homepage are probably more common so I like this better.

**Comment by timvink** [comment]
Thanks for the research and the PR!

**Comment by ewellinger** [comment]
Definitely! Thanks for putting this package together; makes for a really nice way of displaying visualizations in our markdown wiki.

**Comment by timvink** [comment]
Glad to hear, thanks!

**Pull request merged**
